# -*- coding: utf-8 -*-
"""Predictive_Software_Engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9UuhLxZbrXsDehj0S3_yaMcdun-djNp
"""

import pandas as pd

cm1 = pd.read_csv('cm1.csv')
desh = pd.read_csv('desharnais.csv')

print("CM1 shape:", cm1.shape)
print("Desharnais shape:", desh.shape)

cm1.head()
desh.head()

# Remove missing values
cm1 = cm1.dropna()
desh = desh.drop(columns=[col for col in drop_cols if col in desh.columns], errors='ignore')
cm1 = cm1.drop(columns=['id'], errors='ignore')
# Convert defects to binary
cm1['bug'] = cm1['defects'].apply(lambda x: 1 if x > 0 else 0)

# Features and target
X_def = cm1.drop(['defects', 'bug'], axis=1)
y_def = cm1['bug']

# Drop unnecessary columns if present
drop_cols = ['Project', 'Year', 'Language']
desh = desh.drop(columns=[col for col in drop_cols if col in desh.columns], errors='ignore')

# Remove missing values
desh = desh.dropna()

# Convert categorical to numeric
desh = pd.get_dummies(desh, drop_first=True)

# Features and target
X_eff = desh.drop('Effort', axis=1)
y_eff = desh['Effort']

from sklearn.model_selection import train_test_split

# Defect
X_train_d, X_test_d, y_train_d, y_test_d = train_test_split(
    X_def, y_def, test_size=0.2, random_state=42)

# Effort
X_train_e, X_test_e, y_train_e, y_test_e = train_test_split(
    X_eff, y_eff, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

clf = RandomForestClassifier()
clf.fit(X_train_d, y_train_d)

y_pred_d = clf.predict(X_test_d)

print("Defect Accuracy:", accuracy_score(y_test_d, y_pred_d))

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(n_estimators=300, max_depth=12, random_state=42)
}

results = {}
r2_values = []

for name, model in models.items():
    model.fit(X_train_e, y_train_e)
    y_pred = model.predict(X_test_e)

    mae = mean_absolute_error(y_test_e, y_pred)
    r2 = r2_score(y_test_e, y_pred)

    results[name] = (mae, r2)
    r2_values.append(r2)

    print(name)
    print("MAE:", mae)
    print("R2:", r2)
    print("------")

import matplotlib.pyplot as plt

model_names = list(results.keys())

plt.bar(model_names, r2_values)
plt.title("Model Comparison (R2 Score)")
plt.ylabel("R2 Score")
plt.show()

from sklearn.ensemble import RandomForestRegressor

# Instantiate the best model (Random Forest) again using the parameters that yielded the best R2 score.
# This re-creates the model and generates predictions specifically for y_pred_e.
# Parameters are taken from the LrPuKpk3CBm1 cell.
model_rf = RandomForestRegressor(n_estimators=300, max_depth=12, random_state=42)
model_rf.fit(X_train_e, y_train_e)
y_pred_e = model_rf.predict(X_test_e)

plt.scatter(y_test_e, y_pred_e)
plt.xlabel("Actual Effort")
plt.ylabel("Predicted Effort")
plt.title("Actual vs Predicted Effort")
plt.show()

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

models_def = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
}

results_def = {}

for name, model in models_def.items():
    model.fit(X_train_d, y_train_d)
    y_pred = model.predict(X_test_d)

    acc = accuracy_score(y_test_d, y_pred)
    results_def[name] = acc

    print(name)
    print("Accuracy:", acc)
    print("------")

import matplotlib.pyplot as plt

model_names = list(results_def.keys())
acc_values = list(results_def.values())

plt.bar(model_names, acc_values)
plt.title("Defect Prediction Model Comparison")
plt.ylabel("Accuracy")
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns

best_model = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
best_model.fit(X_train_d, y_train_d)

y_pred_best = best_model.predict(X_test_d)

cm = confusion_matrix(y_test_d, y_pred_best)

sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix - Defect Prediction")
plt.show()

from sklearn.metrics import roc_curve, auc

y_prob = best_model.predict_proba(X_test_d)[:,1]

fpr, tpr, _ = roc_curve(y_test_d, y_prob)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label="AUC="+str(roc_auc))
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

import pandas as pd

importances = best_model.feature_importances_

# Use X_train_d.columns for indexing since best_model was trained on X_train_d,
# ensuring the length matches the importances.
feat_imp = pd.Series(importances, index=X_train_d.columns)
feat_imp.sort_values().plot(kind='barh')
plt.title("Feature Importance - Defect Prediction")
plt.show()

# =========================
# 1. IMPORTS
# =========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

from sklearn.metrics import accuracy_score, mean_absolute_error, r2_score
from sklearn.metrics import confusion_matrix, roc_curve, auc

from google.colab import files   # for download

# =========================
# 2. LOAD DATA
# =========================
cm1 = pd.read_csv('cm1.csv')
desh = pd.read_csv('desharnais.csv')

print("CM1 shape:", cm1.shape)
print("Desharnais shape:", desh.shape)

# =========================
# 3. PREPROCESSING
# =========================
cm1 = cm1.dropna()
cm1 = cm1.drop(columns=[col for col in cm1.columns if 'id' in col.lower()], errors='ignore')
cm1['bug'] = cm1['defects'].apply(lambda x: 1 if x > 0 else 0)

X_def = cm1.drop(['defects', 'bug'], axis=1)
y_def = cm1['bug']

drop_cols = ['Project', 'Year', 'Language']
desh = desh.drop(columns=[col for col in drop_cols if col in desh.columns], errors='ignore')
desh = desh.dropna()
desh = pd.get_dummies(desh, drop_first=True)

X_eff = desh.drop('Effort', axis=1)
y_eff = desh['Effort']

# =========================
# 4. SPLIT
# =========================
X_train_d, X_test_d, y_train_d, y_test_d = train_test_split(X_def, y_def, test_size=0.2, random_state=42)
X_train_e, X_test_e, y_train_e, y_test_e = train_test_split(X_eff, y_eff, test_size=0.2, random_state=42)

# =========================
# 5. SCALING
# =========================
scaler = StandardScaler()
X_train_d_scaled = scaler.fit_transform(X_train_d)
X_test_d_scaled = scaler.transform(X_test_d)

# =========================
# 6. DEFECT MODELS
# =========================
models_def = {
    "Logistic Regression": LogisticRegression(max_iter=2000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
}

results_def = {}

for name, model in models_def.items():
    if name == "Logistic Regression":
        model.fit(X_train_d_scaled, y_train_d)
        y_pred = model.predict(X_test_d_scaled)
    else:
        model.fit(X_train_d, y_train_d)
        y_pred = model.predict(X_test_d)

    acc = accuracy_score(y_test_d, y_pred)
    results_def[name] = acc
    print(name, "Accuracy:", acc)

# Save graph
plt.figure()
plt.bar(results_def.keys(), results_def.values())
plt.title("Defect Prediction Model Comparison")
plt.savefig("defect_model.png")
plt.close()

# =========================
# 7. CONFUSION MATRIX
# =========================
best_model = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
best_model.fit(X_train_d, y_train_d)

cm = confusion_matrix(y_test_d, best_model.predict(X_test_d))

plt.figure()
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.savefig("confusion_matrix.png")
plt.close()

# =========================
# 8. ROC CURVE
# =========================
y_prob = best_model.predict_proba(X_test_d)[:,1]
fpr, tpr, _ = roc_curve(y_test_d, y_prob)

plt.figure()
plt.plot(fpr, tpr)
plt.title("ROC Curve")
plt.savefig("roc_curve.png")
plt.close()

# =========================
# 9. FEATURE IMPORTANCE
# =========================
importances = best_model.feature_importances_

plt.figure()
pd.Series(importances, index=X_train_d.columns).sort_values().plot(kind='barh')
plt.title("Feature Importance")
plt.savefig("feature_importance.png")
plt.close()

# =========================
# 10. EFFORT MODELS
# =========================
models_eff = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(n_estimators=300, max_depth=12, random_state=42)
}

r2_values = []

for name, model in models_eff.items():
    model.fit(X_train_e, y_train_e)
    y_pred = model.predict(X_test_e)

    r2 = r2_score(y_test_e, y_pred)
    r2_values.append(r2)
    print(name, "R2:", r2)

plt.figure()
plt.bar(models_eff.keys(), r2_values)
plt.title("Effort Model Comparison")
plt.savefig("effort_model.png")
plt.close()

# =========================
# 11. SCATTER
# =========================
rf = RandomForestRegressor(n_estimators=300, max_depth=12, random_state=42)
rf.fit(X_train_e, y_train_e)

y_pred_e = rf.predict(X_test_e)

plt.figure()
plt.scatter(y_test_e, y_pred_e)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted Effort")
plt.savefig("scatter.png")
plt.close()

# =========================
# 12. DOWNLOAD ALL FILES
# =========================
files.download("defect_model.png")
files.download("confusion_matrix.png")
files.download("roc_curve.png")
files.download("feature_importance.png")
files.download("effort_model.png")
files.download("scatter.png")